### GET the list of actors of a movie
GET {{host}}/movies/6bcbca1e-efd3-411d-9f7c-14b872444fce/actors

### GET the list of actors of a movie
GET {{host}}/movies/xxxx/actors

###
GET {{host}}/directors?director=Zack%20Snyder


